### PR TITLE
ci: add azure pipelines CI and smoketest

### LINKED ISSUE #4: [FEAT] CI Pipeline
# :bulb: Feature request

## Feature Name

CI Pipeline

## The Desired Behavior

I want this repo to have CI.

### PR DESCRIPTION
**Pull request by griest024**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/magento2-daffodil/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[x] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

Fixes: #4 

## What is the new behavior?
- Adds CI with azure pipelines
- Adds smoketests

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by damienwebdev** [comment]
Needs a rebase. I committed a `composer.lock`

**Comment by griest024** [comment]
> Needs a rebase. I committed a `composer.lock`

rebased

**Comment by damienwebdev** [comment]
Sorry, I made a mistake in committing the old `composer.lock`. This needs one more rebase.

**Comment by griest024** [comment]
> Sorry, I made a mistake in committing the old `composer.lock`. This needs one more rebase.

done

**Review by damienwebdev — APPROVED** [review]
lgtm

**Pull request merged**
